### ISSUE TITLE
Make login text clearer

### ISSUE THREAD

**Issue by kpolrr** [mario872/sentralify#3]
When logging in, I found that I could log in with NSW as the state but not New South Wales. I don't know if this is user error or an error in the code, but it could be better to tell the user to use the abbreviation

**Comment by mario872** [comment]
Good point. Currently the state is only used for determining the user's email (john.doe@education.state.gov.au). I'll change the README / docs to make it clearer that they should use the abbreviation.

**Comment by mario872** [comment]
Does this look good to you @kpolrr?

**Comment by kpolrr** [comment]
Yeah thats good
